name: CI
on:
  push:
  pull_request:
jobs:
  main:
    strategy:
      matrix:
        node: [10.13, 12, 14, 15]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm install

      - name: Test
        run: npm test

  release:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'eps1lon/testing-library-envinfo' && contains('refs/heads/main', github.ref) && github.event_name == 'push' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
